[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "flake8>=7.4.1",
    "flake8-pyproject>=1.2.4",
    "llm-sdk>=0.1.0",
    "mypy>=2.4.0",
    "numpy>=2.2.6",
    "pydantic>=2.13.5",
    "torch>=2.14.1",
    "transformers>=5.18.0",
]

[tool.black]
line-length = 79   

[tool.flake8]
exclude = [".venv", "venv", "llm_sdk", "moulinette"]

[tool.mypy]
exclude = [".venv", "venv", "llm_sdk", "moulinette"]

[tool.uv.sources]
llm_sdk = { path = "llm_sdk", editable = true }
